version: 2
updates:
  # TypeScript dependencies
  - package-ecosystem: "npm"
    directory: "/implementation/typescript"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "krhrtky"
    assignees:
      - "krhrtky"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    open-pull-requests-limit: 5

  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/implementation/rust"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "krhrtky"
    assignees:
      - "krhrtky"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "krhrtky"
    assignees:
      - "krhrtky"
    commit-message:
      prefix: "chore(ci):"
      include: "scope"
    open-pull-requests-limit: 3