openapi: 3.0.3
info:
  title: External Reference Test API
  description: API for testing external OpenAPI file reference support
  version: 1.0.0

paths:
  /users:
    post:
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schema-composition-test-api.yaml#/components/schemas/UserProfile'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: './schema-composition-test-api.yaml#/components/schemas/UserProfile'

  /products:
    post:
      summary: Create a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schema-composition-test-api.yaml#/components/schemas/PhysicalProduct'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: './schema-composition-test-api.yaml#/components/schemas/PhysicalProduct'

components:
  schemas:
    LocalSchema:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          description: Local schema identifier
        name:
          type: string
          description: Local schema name